### PR TITLE
Fix circular dependencies

### LINKED ISSUE #425: Fix circular dependencies
The following circular dependencies are reported by rollup. We should clean them up.

```
src/utils/url.ts -> src/utils/normalize-url.ts -> src/utils/url.ts
src/discovery/index.ts -> src/discovery/discovery-service.ts -> src/index.ts -> src/discovery/index.ts
src/jellyfin.ts -> src/discovery/index.ts -> src/discovery/discovery-service.ts -> src/index.ts -> src/jellyfin.ts
```

### PR DESCRIPTION
**Pull request by thornbill**
Updates a bunch of imports and moves some constants to dedicated files to avoid circular dependencies

Fixes #425

### CODE REVIEW

File: src/versions.ts [hunk 1]
```diff
@@ -0,0 +1,11 @@
...
+ * This Source Code Form is subject to the terms of the Mozilla Public
+ * License, v. 2.0. If a copy of the MPL was not distributed with this
+ * file, You can obtain one at http://mozilla.org/MPL/2.0/.
+ */
+
+/** The current API version of the generated client. */
+export const API_VERSION = '10.8.9';
+
+/** The minimum supported server version. */
+export const MINIMUM_VERSION = '10.8.0';
```
Comment (nielsvanvelzen) [inline src/versions.ts]: Shouldn't this be 10.8.1? The README says so at least

Comment (thornbill) [reply src/versions.ts]: Yeah that's a good point. I had left it there intentionally originally since TS/JS are a bit more forgiving with the API change that happened in 10.8.1, but it's probably time to move on at this point.

**Review by nielsvanvelzen — APPROVED** [review]
